NewMPCReal:
  time_step: 1.0         # Time step for MPC
  human_max_speed: 1.5   # Maximum speed of humans
  horizon: 15            # Time horizon for MPC
  other_param: 42        # Example additional parameter
